motley-php: Motley\Test\UsageFormatterTest Class Reference
Motley\Test\UsageFormatterTest Class Reference
Tests the Motley::UsageFormatter class.
Public Member Functions
testNew ()
Test instantiation.
testClearOutput ()
test clear and output.
testFormatting ()
Test formatting.
testSetGetColumnWidth ()
test set/get column width.
testSetGetLeftIndent ()
test set/get left indent.
testSetGetRightIndent ()
test set/get right indent.
testSetGetContIndent ()
test set/get continue indent.
testSetGetMaxLength ()
test set/get max length.
testSetGetEOL ()
test set/get eol.
testGetSetParam ()
Test get/get param.
Detailed Description
Tests the Motley::UsageFormatter class.
Definition at line 15 of file UsageFormatterTest.php.
Member Function Documentation
testNew()
Motley\Test\UsageFormatterTest::testNew ()
Test instantiation.
Definition at line 18 of file UsageFormatterTest.php.
testClearOutput()
Motley\Test\UsageFormatterTest::testClearOutput ()
test clear and output.
Definition at line 24 of file UsageFormatterTest.php.
testFormatting()
Motley\Test\UsageFormatterTest::testFormatting ()
Test formatting.
Definition at line 41 of file UsageFormatterTest.php.
testSetGetColumnWidth()
Motley\Test\UsageFormatterTest::testSetGetColumnWidth ()
test set/get column width.
Definition at line 138 of file UsageFormatterTest.php.
testSetGetLeftIndent()
Motley\Test\UsageFormatterTest::testSetGetLeftIndent ()
test set/get left indent.
Definition at line 147 of file UsageFormatterTest.php.
testSetGetRightIndent()
Motley\Test\UsageFormatterTest::testSetGetRightIndent ()
test set/get right indent.
Definition at line 156 of file UsageFormatterTest.php.
testSetGetContIndent()
Motley\Test\UsageFormatterTest::testSetGetContIndent ()
test set/get continue indent.
Definition at line 165 of file UsageFormatterTest.php.
testSetGetMaxLength()
Motley\Test\UsageFormatterTest::testSetGetMaxLength ()
test set/get max length.
Definition at line 174 of file UsageFormatterTest.php.
testSetGetEOL()
Motley\Test\UsageFormatterTest::testSetGetEOL ()
test set/get eol.
Definition at line 188 of file UsageFormatterTest.php.
testGetSetParam()
Motley\Test\UsageFormatterTest::testGetSetParam ()
Test get/get param.
Definition at line 196 of file UsageFormatterTest.php.
References Motley\UnitTestSupport\disengageCaptureHandler(), Motley\UnitTestSupport\engageCaptureHandler(), Motley\UnitTestSupport\getCapturedErrors(), Motley\UnitTestSupport\invokeFunction(), and Motley\UsageFormatter\LEFT_INDENT.
The documentation for this class was generated from the following file:
phplib/Motley/Test/UsageFormatterTest.php