motley-php: Motley\Autoloader Class Reference
Motley\Autoloader Class Reference
Static routines to support Motley autoloading.
Static Public Member Functions
static autoload (string $class_name)
Attempt to find source file from class name, and if found, include the file.
static register ()
Registers the Motley::Autoloader::autoload routine as an autoloader.
static unregister ()
Un-registers the Motley::Autoloader::autoload routine as an autoloader.
static isRegistered ()
Check if Motley::Autoloader::autoload is SPL registered.
Data Fields
const AutoloadClassName = "Motley\Autoloader"
Our autoloader class name.
const AutoloadFunctionName = "autoload"
Out autoloader function name.
Detailed Description
Static routines to support Motley autoloading.
Definition at line 11 of file Autoloader.php.
Member Function Documentation
autoload()
static Motley\Autoloader::autoload (string $class_name) static
Attempt to find source file from class name, and if found, include the file.
Parameters
$class_name - The string class name of a class.
Returns
Returns false if no good file match found.
Definition at line 18 of file Autoloader.php.
Referenced by Motley\Test\AutoloaderTest\testAutoload().
register()
static Motley\Autoloader::register () static
Registers the Motley::Autoloader::autoload routine as an autoloader.
Returns
TRUE on success, else FALSE.
Definition at line 43 of file Autoloader.php.
Referenced by Motley\Autoloader\isRegistered(), Motley\Test\AutoloaderTest\tearDown(), Motley\Test\AutoloaderTest\testAutoload(), and Motley\Test\AutoloaderTest\testRegisterFunction().
unregister()
static Motley\Autoloader::unregister () static
Un-registers the Motley::Autoloader::autoload routine as an autoloader.
Returns
TRUE on success, else FALSE.
Definition at line 53 of file Autoloader.php.
Referenced by Motley\Test\AutoloaderTest\setUp(), Motley\Test\AutoloaderTest\testAutoload(), and Motley\Test\AutoloaderTest\testRegisterFunction().
isRegistered()
static Motley\Autoloader::isRegistered () static
Check if Motley::Autoloader::autoload is SPL registered.
Returns
TRUE if registered
Definition at line 63 of file Autoloader.php.
References Motley\Autoloader\register().
Referenced by Motley\Test\AutoloaderTest\testRegisterFunction().
Field Documentation
AutoloadClassName
const Motley\Autoloader::AutoloadClassName = "Motley\Autoloader"
Our autoloader class name.
Definition at line 12 of file Autoloader.php.
AutoloadFunctionName
const Motley\Autoloader::AutoloadFunctionName = "autoload"
Out autoloader function name.
Definition at line 13 of file Autoloader.php.
The documentation for this class was generated from the following file:
phplib/Motley/Autoloader.php