motley-php: Motley\CommandOpt Class Reference
Motley\CommandOpt Class Reference
Represent a command line option.
Public Member Functions
__construct (string $name=null, string $desc=null, array $switches=null)
Class instance constructor.
addOptSwitches (array $switches)
Add an array of switch synonyms.
getOptSwitches ()
Get the list of switch synonyms.
clearOptSwitches ()
Clear all switch synonyms.
setOptArg (CommandArg $argObj=null, bool $isOpt=false)
Set the option argument, if any.
getOptArg ()
Get the option argument, if any.
getOptArgOptional ()
Get the option argument optional flag.
getSwitchesString ()
Get switches display string.
validate (string $param)
Validate a command line option switch (and argument).
getName ()
Get the object name.
setName (string $name)
Set the object name.
getDescription ()
Get the object description.
setDescription (string $desc)
Set the object description.
getDisplayName ()
Get the display name.
setDisplayName ($dispName)
Set the display name.
getLastParamValue ()
get the last param value.
getLastParamIsValid ()
get the last param is valid flag.
getLastParamMessage ()
get the last param message.
getValidParamHistory ()
Get the valid params history.
resetValidParamHistory ()
Reset the valid params history.
Static Public Member Functions
static checkOptSwitch (string $switch)
Check option switch format.
static findComponentByName (string $name, array $components)
Find component(s) by name from an array of Motley::CommandComponent objects.
Protected Member Functions
saveLastParam ($param, bool $isValid, string $message)
Save the last command line parameter processed.
Protected Attributes
$optSwitches = array()
Option switch synonyms.
$optArgument = null
Option argument, if any.
$optArgOptional = false
Is option argument optional.
$name = ""
Object name.
$description = ""
Object description.
$displayName = null
Object display name.
$lastParamValue = ""
The last param value.
$lastParamIsValid = false
Was the last param valid.
$lastParamMessage = ""
Possible error message about last param.
$validParamHist = array()
All valid params validated since reset.
$chkW = null
Warning checker.
$chkE = null
Error checker.
Detailed Description
Represent a command line option.
Definition at line 13 of file CommandOpt.php.
Constructor & Destructor Documentation
__construct()
Motley\CommandOpt::__construct (string $name = null, string $desc = null, array $switches = null)
Class instance constructor.
Parameters
$name - optional name for option.
$desc - optional description for option.
$switches - optional array of switches.
Definition at line 23 of file CommandOpt.php.
Member Function Documentation
addOptSwitches()
Motley\CommandOpt::addOptSwitches (array $switches)
Add an array of switch synonyms.
If a switch is already on the switch list, then it is ignored.
Parameters
$switches - An array of string values.
Returns
New number of switch synonyms defined.
Definition at line 36 of file CommandOpt.php.
getOptSwitches()
Motley\CommandOpt::getOptSwitches ()
Get the list of switch synonyms.
Returns
The list of switch synonyms.
Definition at line 52 of file CommandOpt.php.
Referenced by Motley\CommandOptGrp\addOption().
clearOptSwitches()
Motley\CommandOpt::clearOptSwitches ()
Clear all switch synonyms.
Definition at line 57 of file CommandOpt.php.
setOptArg()
Motley\CommandOpt::setOptArg (CommandArg $argObj = null, bool $isOpt = false)
Set the option argument, if any.
Parameters
$argObj - An instance of Motley::CommandArg.
$isOpt - Is the argument portion of this option optional?
Definition at line 64 of file CommandOpt.php.
getOptArg()
Motley\CommandOpt::getOptArg ()
Get the option argument, if any.
Returns
An instance of Motley::CommandArg or null.
Definition at line 71 of file CommandOpt.php.
getOptArgOptional()
Motley\CommandOpt::getOptArgOptional ()
Get the option argument optional flag.
Returns
True if the associated option argument is optional, else false;
Definition at line 77 of file CommandOpt.php.
getSwitchesString()
Motley\CommandOpt::getSwitchesString ()
Get switches display string.
Returns
A textual notation for the option.
Definition at line 83 of file CommandOpt.php.
validate()
Motley\CommandOpt::validate (string $param)
Validate a command line option switch (and argument).
Parameters
$param - A command line parameter.
Returns
TRUE if $param is valid, else FALSE.
Definition at line 139 of file CommandOpt.php.
checkOptSwitch()
static Motley\CommandOpt::checkOptSwitch (string $switch) static
Check option switch format.
Parameters
$switch - The switch to check.
Returns
True is switch format is ok, else false.
Definition at line 236 of file CommandOpt.php.
Referenced by Motley\Test\CommandOptTest\testCheckOptSwitch().
getName()
Motley\CommandComponent::getName () inherited
Get the object name.
Returns
the object name.
Definition at line 41 of file CommandComponent.php.
Referenced by Motley\CommandOptGrp\addOption().
setName()
Motley\CommandComponent::setName (string $name) inherited
Set the object name.
Parameters
$name - The object name.
Definition at line 47 of file CommandComponent.php.
getDescription()
Motley\CommandComponent::getDescription () inherited
Get the object description.
Returns
the object description.
Definition at line 53 of file CommandComponent.php.
setDescription()
Motley\CommandComponent::setDescription (string $desc) inherited
Set the object description.
Parameters
$desc - the object description.
Definition at line 59 of file CommandComponent.php.
getDisplayName()
Motley\CommandComponent::getDisplayName () inherited
Get the display name.
Returns
the display name.
Definition at line 65 of file CommandComponent.php.
setDisplayName()
Motley\CommandComponent::setDisplayName ($dispName) inherited
Set the display name.
Parameters
$dispName - The display name.
Definition at line 75 of file CommandComponent.php.
saveLastParam()
Motley\CommandComponent::saveLastParam ($param, bool $isValid, string $message) protected inherited
Save the last command line parameter processed.
Parameters
$param - The command line parameter.
$isValid - True if $param meets validation requirements.
$message - Explain why $param is or is not valid.
Definition at line 83 of file CommandComponent.php.
getLastParamValue()
Motley\CommandComponent::getLastParamValue () inherited
get the last param value.
Returns
The last command line parameter processed.
Definition at line 96 of file CommandComponent.php.
getLastParamIsValid()
Motley\CommandComponent::getLastParamIsValid () inherited
get the last param is valid flag.
Returns
The last command line parameter is valid flag.
Definition at line 102 of file CommandComponent.php.
getLastParamMessage()
Motley\CommandComponent::getLastParamMessage () inherited
get the last param message.
Returns
The last command line parameter message.
Definition at line 108 of file CommandComponent.php.
getValidParamHistory()
Motley\CommandComponent::getValidParamHistory () inherited
Get the valid params history.
Returns
Array of all valid params validated since last reset.
Definition at line 124 of file CommandComponent.php.
resetValidParamHistory()
Motley\CommandComponent::resetValidParamHistory () inherited
Reset the valid params history.
Definition at line 129 of file CommandComponent.php.
findComponentByName()
static Motley\CommandComponent::findComponentByName (string $name, array $components) static inherited
Find component(s) by name from an array of Motley::CommandComponent objects.
Parameters
$name - The name of the component.
$components - An array of Motley::CommandComponent objects. This includes Motley::CommandArg, Motley::CommandOpt, Motley::CommandOptGrp, and Motley::CommandDoubleDash.
Returns
An array of components that matched the name.
Definition at line 141 of file CommandComponent.php.
Referenced by Motley\Test\CommandComponentTest\testFindComponentByName().
Field Documentation
$optSwitches
Motley\CommandOpt::$optSwitches = array() protected
Option switch synonyms.
Definition at line 15 of file CommandOpt.php.
$optArgument
Motley\CommandOpt::$optArgument = null protected
Option argument, if any.
Definition at line 16 of file CommandOpt.php.
$optArgOptional
Motley\CommandOpt::$optArgOptional = false protected
Is option argument optional.
Definition at line 17 of file CommandOpt.php.
$name
Motley\CommandComponent::$name = "" protected inherited
Object name.
Definition at line 15 of file CommandComponent.php.
$description
Motley\CommandComponent::$description = "" protected inherited
Object description.
Definition at line 16 of file CommandComponent.php.
$displayName
Motley\CommandComponent::$displayName = null protected inherited
Object display name.
Definition at line 17 of file CommandComponent.php.
$lastParamValue
Motley\CommandComponent::$lastParamValue = "" protected inherited
The last param value.
Definition at line 18 of file CommandComponent.php.
$lastParamIsValid
Motley\CommandComponent::$lastParamIsValid = false protected inherited
Was the last param valid.
Definition at line 19 of file CommandComponent.php.
$lastParamMessage
Motley\CommandComponent::$lastParamMessage = "" protected inherited
Possible error message about last param.
Definition at line 20 of file CommandComponent.php.
$validParamHist
Motley\CommandComponent::$validParamHist = array() protected inherited
All valid params validated since reset.
Definition at line 21 of file CommandComponent.php.
$chkW
Motley\CommandComponent::$chkW = null protected inherited
Warning checker.
Definition at line 22 of file CommandComponent.php.
$chkE
Motley\CommandComponent::$chkE = null protected inherited
Error checker.
Definition at line 23 of file CommandComponent.php.
The documentation for this class was generated from the following file:
phplib/Motley/CommandOpt.php