motley-php: Motley\Test\CommandComponentTest Class Reference
Motley\Test\CommandComponentTest Class Reference
Tests the Motley::CommandComponent class.
Public Member Functions
testNew ()
Test instantiation.
testSetGetName ()
Test setName/getName functions.
testSetGetDescription ()
Test setDescription/getDescription functions.
testSetGetDisplayName ()
Test set/get display name functions.
testSaveLastParam ()
Test save last param function.
testValiateGetLastParam ()
Test validate and get last parameter functions.
testParamHistory ()
Test validate and parameter history functions.
testFindComponentByName ()
Test static function findComponentByName.
Detailed Description
Tests the Motley::CommandComponent class.
Definition at line 15 of file CommandComponentTest.php.
Member Function Documentation
testNew()
Motley\Test\CommandComponentTest::testNew ()
Test instantiation.
Definition at line 18 of file CommandComponentTest.php.
testSetGetName()
Motley\Test\CommandComponentTest::testSetGetName ()
Test setName/getName functions.
Definition at line 24 of file CommandComponentTest.php.
testSetGetDescription()
Motley\Test\CommandComponentTest::testSetGetDescription ()
Test setDescription/getDescription functions.
Definition at line 34 of file CommandComponentTest.php.
testSetGetDisplayName()
Motley\Test\CommandComponentTest::testSetGetDisplayName ()
Test set/get display name functions.
Definition at line 44 of file CommandComponentTest.php.
testSaveLastParam()
Motley\Test\CommandComponentTest::testSaveLastParam ()
Test save last param function.
Definition at line 54 of file CommandComponentTest.php.
References Motley\UnitTestSupport\invokeFunction().
testValiateGetLastParam()
Motley\Test\CommandComponentTest::testValiateGetLastParam ()
Test validate and get last parameter functions.
Definition at line 73 of file CommandComponentTest.php.
testParamHistory()
Motley\Test\CommandComponentTest::testParamHistory ()
Test validate and parameter history functions.
Definition at line 83 of file CommandComponentTest.php.
References Motley\UnitTestSupport\invokeFunction().
testFindComponentByName()
Motley\Test\CommandComponentTest::testFindComponentByName ()
Test static function findComponentByName.
Definition at line 113 of file CommandComponentTest.php.
References Motley\CommandComponent\findComponentByName().
The documentation for this class was generated from the following file:
phplib/Motley/Test/CommandComponentTest.php