motley-php: Motley\Test\AutoloaderTest Class Reference
Motley\Test\AutoloaderTest Class Reference
Tests the Motley::Autoloader class.
Public Member Functions
testRegisterFunction ()
Test register and unregister.
testAutoload ()
Test invoking autoload directly.
Protected Member Functions
setUp ()
A unit test set-uo function to initialize some tests.
tearDown ()
A unit test tear-down function to possibly restore autoloaders.
Detailed Description
Tests the Motley::Autoloader class.
Definition at line 15 of file AutoloaderTest.php.
Member Function Documentation
setUp()
Motley\Test\AutoloaderTest::setUp () protected
A unit test set-uo function to initialize some tests.
Definition at line 18 of file AutoloaderTest.php.
References Motley\Autoloader\unregister().
tearDown()
Motley\Test\AutoloaderTest::tearDown () protected
A unit test tear-down function to possibly restore autoloaders.
Definition at line 23 of file AutoloaderTest.php.
References Motley\Autoloader\register().
testRegisterFunction()
Motley\Test\AutoloaderTest::testRegisterFunction ()
Test register and unregister.
Definition at line 28 of file AutoloaderTest.php.
References Motley\Autoloader\isRegistered(), Motley\Autoloader\register(), and Motley\Autoloader\unregister().
testAutoload()
Motley\Test\AutoloaderTest::testAutoload ()
Test invoking autoload directly.
Definition at line 40 of file AutoloaderTest.php.
References Motley\Autoloader\autoload(), Motley\Autoloader\register(), and Motley\Autoloader\unregister().
The documentation for this class was generated from the following file:
phplib/Motley/Test/AutoloaderTest.php