motley-php: Motley\UnitTestSupport Class Reference
Motley\UnitTestSupport Class Reference
Routines to support unit test routines.
Public Member Functions
__construct ()
CLass constructor.
setTmpDirRoot (string $rootDir)
Set the base temporary directory.
getTmpDirRoot ()
Get the base temporary directory.
createTmpRootDir ()
Create the root temporary directory if it does not yet exist.
createTmpSubDir (string $relSubDir=null)
Create a temporary subdirectory under the root temporary directory.
createTmpDummyFile (string $filespec, string $dummy="", int $repeat=0)
Create a temporary dummy file.
getTmpDirsCreated ()
Get the list of temp directories actually created.
getTmpFilesCreated ()
Get the list of temp files actually created.
cleanupTmp ()
Delete as much of tmp work as possible.
recursiveRmdir (string $path)
Recursively delete a directory and all contents.
Static Public Member Functions
static invokeFunction (&$obj, $funcName, array $argArr=array())
Call a protected or private function in a class under test.
static errorHandlerForCapturing (int $errno, string $errstr, string $errfile, int $errline)
An error handler which simply captures the errors.
static engageCaptureHandler (int $error_types=E_ALL|E_STRICT)
Set the capture error handler as an active error handler.
static disengageCaptureHandler ()
Disengage the capture handler and restore the original handler.
static getCapturedErrors ()
Get all captured errors as an array of hash arrays.
static clearCapturedErrors ()
Clear all captured errors.
Data Fields
const ERRNO = "errno"
Error hash key for error level.
const ERRSTR = "errstr"
Error hash key for error message.
const ERRFILE = "errfile"
Error hash key for source code file.
const ERRLINE = "errline"
Error hash key for file line number.
Static Public Attributes
static $capturedErrors = array()
An array of hash arrays of captured errors.
static $captureHandlerSet = false
Keep track of whether the capture error handler is engaged.
static $oldErrorHandler = null
The saved old error handler, if it is replaced.
Protected Attributes
$tmpRootDir = null
Root temporary directory.
$tmpDirsCreated = array()
Temp dirs created in session.
$tmpFilesCreated = array()
Temp files created in session.
$chkE = null
Checker instance for errors.
Detailed Description
Routines to support unit test routines.
Definition at line 13 of file UnitTestSupport.php.
Constructor & Destructor Documentation
__construct()
Motley\UnitTestSupport::__construct ()
CLass constructor.
Definition at line 101 of file UnitTestSupport.php.
Member Function Documentation
invokeFunction()
static Motley\UnitTestSupport::invokeFunction (& $obj, $funcName, array $argArr = array()) static
Call a protected or private function in a class under test.
This is a unit test helper function.
Parameters
$obj - A class object.
$funcName - The name of the function to call.
$argArr - Array of function arguments.
Returns
Whatever the called function returns.
Definition at line 35 of file UnitTestSupport.php.
Referenced by Motley\Test\UsageFormatterTest\testGetSetParam(), Motley\Test\UnitTestSupportTest\testInvokeFunction(), Motley\Test\CommandComponentTest\testParamHistory(), and Motley\Test\CommandComponentTest\testSaveLastParam().
errorHandlerForCapturing()
static Motley\UnitTestSupport::errorHandlerForCapturing (int $errno, string $errstr, string $errfile, int $errline) static
An error handler which simply captures the errors.
Parameters
$errno - The error level.
$errstr - The error message.
$errfile - The error file.
$errline - The error line.
Returns
Always returns TRUE.
Definition at line 49 of file UnitTestSupport.php.
engageCaptureHandler()
static Motley\UnitTestSupport::engageCaptureHandler (int $error_types = E_ALL|E_STRICT) static
Set the capture error handler as an active error handler.
Parameters
$error_types - AN error level mask for errors calling this handler.
Returns
Nothing returned.
Definition at line 63 of file UnitTestSupport.php.
Referenced by Motley\Test\CommandOptGrpTest\testAddGetClearOptSwitches(), Motley\Test\UnitTestSupportTest\testCaptureHandler(), Motley\Test\CheckerTest\testChecking(), and Motley\Test\UsageFormatterTest\testGetSetParam().
disengageCaptureHandler()
static Motley\UnitTestSupport::disengageCaptureHandler () static
Disengage the capture handler and restore the original handler.
Returns
Nothing returned.
Definition at line 72 of file UnitTestSupport.php.
Referenced by Motley\Test\CommandOptGrpTest\testAddGetClearOptSwitches(), Motley\Test\UnitTestSupportTest\testCaptureHandler(), Motley\Test\CheckerTest\testChecking(), and Motley\Test\UsageFormatterTest\testGetSetParam().
getCapturedErrors()
static Motley\UnitTestSupport::getCapturedErrors () static
Get all captured errors as an array of hash arrays.
Returns
An array of hash arrays. Each hash array describes a captured error using "errno", "srrstr", "errfile" and "errline" keys.
Definition at line 82 of file UnitTestSupport.php.
Referenced by Motley\Test\CommandOptGrpTest\testAddGetClearOptSwitches(), Motley\Test\UnitTestSupportTest\testCaptureHandler(), Motley\Test\CheckerTest\testChecking(), and Motley\Test\UsageFormatterTest\testGetSetParam().
clearCapturedErrors()
static Motley\UnitTestSupport::clearCapturedErrors () static
Clear all captured errors.
Returns
Nothing returned.
Definition at line 88 of file UnitTestSupport.php.
Referenced by Motley\Test\UnitTestSupportTest\testCaptureHandler(), and Motley\Test\CheckerTest\testChecking().
setTmpDirRoot()
Motley\UnitTestSupport::setTmpDirRoot (string $rootDir)
Set the base temporary directory.
Parameters
$rootDir - The absolute path to the root temporary directory.
Definition at line 108 of file UnitTestSupport.php.
getTmpDirRoot()
Motley\UnitTestSupport::getTmpDirRoot ()
Get the base temporary directory.
Returns
The absolute path to the root temporary directory.
Definition at line 114 of file UnitTestSupport.php.
createTmpRootDir()
Motley\UnitTestSupport::createTmpRootDir ()
Create the root temporary directory if it does not yet exist.
Returns
The absolute path to the root temporary directory.
Definition at line 120 of file UnitTestSupport.php.
createTmpSubDir()
Motley\UnitTestSupport::createTmpSubDir (string $relSubDir = null)
Create a temporary subdirectory under the root temporary directory.
Parameters
$relSubDir - The optional relative name of the subdirectory. If not specified, a randomly named subdirectory will be created.
Returns
The absolute path of the created subdirectory.
Definition at line 134 of file UnitTestSupport.php.
createTmpDummyFile()
Motley\UnitTestSupport::createTmpDummyFile (string $filespec, string $dummy = "", int $repeat = 0)
Create a temporary dummy file.
Parameters
$filespec - absolute file path for temporary file. However, it must be in a temporary directory we created.
$dummy - An optional string to be optionally repeated in the file.
$repeat - The number of times to repeat $dummy.
Returns
The absolute path of the file created.
Definition at line 154 of file UnitTestSupport.php.
getTmpDirsCreated()
Motley\UnitTestSupport::getTmpDirsCreated ()
Get the list of temp directories actually created.
Returns
The list of temp directories actually created.
Definition at line 176 of file UnitTestSupport.php.
getTmpFilesCreated()
Motley\UnitTestSupport::getTmpFilesCreated ()
Get the list of temp files actually created.
Returns
The list of temp files actually created.
Definition at line 182 of file UnitTestSupport.php.
cleanupTmp()
Motley\UnitTestSupport::cleanupTmp ()
Delete as much of tmp work as possible.
Definition at line 187 of file UnitTestSupport.php.
recursiveRmdir()
Motley\UnitTestSupport::recursiveRmdir (string $path)
Recursively delete a directory and all contents.
Parameters
$path - The top level directory to remove.
Definition at line 207 of file UnitTestSupport.php.
Field Documentation
ERRNO
const Motley\UnitTestSupport::ERRNO = "errno"
Error hash key for error level.
Definition at line 15 of file UnitTestSupport.php.
ERRSTR
const Motley\UnitTestSupport::ERRSTR = "errstr"
Error hash key for error message.
Definition at line 16 of file UnitTestSupport.php.
Referenced by Motley\Test\UnitTestSupportTest\testCaptureHandler().
ERRFILE
const Motley\UnitTestSupport::ERRFILE = "errfile"
Error hash key for source code file.
Definition at line 17 of file UnitTestSupport.php.
ERRLINE
const Motley\UnitTestSupport::ERRLINE = "errline"
Error hash key for file line number.
Definition at line 18 of file UnitTestSupport.php.
$capturedErrors
Motley\UnitTestSupport::$capturedErrors = array() static
An array of hash arrays of captured errors.
Each hash array has the following keys: "errno", "errstr", "errfile", and "errline".
Definition at line 23 of file UnitTestSupport.php.
$captureHandlerSet
Motley\UnitTestSupport::$captureHandlerSet = false static
Keep track of whether the capture error handler is engaged.
Definition at line 25 of file UnitTestSupport.php.
Referenced by Motley\Test\CheckerTest\tearDown(), Motley\Test\UnitTestSupportTest\tearDown(), and Motley\Test\CommandMessengerTest\tearDown().
$oldErrorHandler
Motley\UnitTestSupport::$oldErrorHandler = null static
The saved old error handler, if it is replaced.
Definition at line 27 of file UnitTestSupport.php.
$tmpRootDir
Motley\UnitTestSupport::$tmpRootDir = null protected
Root temporary directory.
Definition at line 95 of file UnitTestSupport.php.
$tmpDirsCreated
Motley\UnitTestSupport::$tmpDirsCreated = array() protected
Temp dirs created in session.
Definition at line 96 of file UnitTestSupport.php.
$tmpFilesCreated
Motley\UnitTestSupport::$tmpFilesCreated = array() protected
Temp files created in session.
Definition at line 97 of file UnitTestSupport.php.
$chkE
Motley\UnitTestSupport::$chkE = null protected
Checker instance for errors.
Definition at line 98 of file UnitTestSupport.php.
The documentation for this class was generated from the following file:
phplib/Motley/UnitTestSupport.php