motley-php: Motley\Test\CheckerTest Class Reference
Motley\Test\CheckerTest Class Reference
Tests the Motley::Checker class.
Public Member Functions
testGetSetErrorLevel ()
Test get/set checker error level.
testChecking ()
Test various checker functions.
testIsAssociativeArray ()
Test the isAssociativeArray static function.
testDescribeVar ()
Test the describeVar static function.
Protected Member Functions
tearDown ()
A unit test tear-down function to clean up possible test error handlers.
Detailed Description
Tests the Motley::Checker class.
Definition at line 15 of file CheckerTest.php.
Member Function Documentation
tearDown()
Motley\Test\CheckerTest::tearDown () protected
A unit test tear-down function to clean up possible test error handlers.
Definition at line 19 of file CheckerTest.php.
References Motley\UnitTestSupport\$captureHandlerSet.
testGetSetErrorLevel()
Motley\Test\CheckerTest::testGetSetErrorLevel ()
Test get/set checker error level.
Definition at line 29 of file CheckerTest.php.
testChecking()
Motley\Test\CheckerTest::testChecking ()
Test various checker functions.
Definition at line 42 of file CheckerTest.php.
References Motley\UnitTestSupport\clearCapturedErrors(), Motley\UnitTestSupport\disengageCaptureHandler(), Motley\UnitTestSupport\engageCaptureHandler(), and Motley\UnitTestSupport\getCapturedErrors().
testIsAssociativeArray()
Motley\Test\CheckerTest::testIsAssociativeArray ()
Test the isAssociativeArray static function.
Definition at line 250 of file CheckerTest.php.
References Motley\Checker\isAssociativeArray().
testDescribeVar()
Motley\Test\CheckerTest::testDescribeVar ()
Test the describeVar static function.
Definition at line 266 of file CheckerTest.php.
References Motley\Checker\describeVar().
The documentation for this class was generated from the following file:
phplib/Motley/Test/CheckerTest.php