motley-php: Motley\Test\UnitTestSupportTest Class Reference
Motley\Test\UnitTestSupportTest Class Reference
Tests the Motley::UnitTestSupport class.
Public Member Functions
testInvokeFunction ()
Test invokeFunction.
testCaptureHandler ()
Test the capture error handler.
testRecursiveDirectoryDelete ()
Test the temporary dir/file routines.
Protected Member Functions
tearDown ()
A unit test tear-down function to clean up possible test error handlers.
Protected Attributes
$lastUnit = null
Last interesting UnitTestSupport instance.
Detailed Description
Tests the Motley::UnitTestSupport class.
Definition at line 17 of file UnitTestSupportTest.php.
Member Function Documentation
tearDown()
Motley\Test\UnitTestSupportTest::tearDown () protected
A unit test tear-down function to clean up possible test error handlers.
Definition at line 23 of file UnitTestSupportTest.php.
References Motley\UnitTestSupport\$captureHandlerSet.
testInvokeFunction()
Motley\Test\UnitTestSupportTest::testInvokeFunction ()
Test invokeFunction.
Definition at line 36 of file UnitTestSupportTest.php.
References Motley\UnitTestSupport\invokeFunction(), Motley\Test\ZzzSampleClass\PRIFUN, Motley\Test\ZzzSampleClass\PROFUN, Motley\Test\ZzzSampleClass\PUBFUN, Motley\Test\ZzzSampleClass\STAPRIFUN, Motley\Test\ZzzSampleClass\STAPROFUN, and Motley\Test\ZzzSampleClass\STAPUBFUN.
testCaptureHandler()
Motley\Test\UnitTestSupportTest::testCaptureHandler ()
Test the capture error handler.
Definition at line 53 of file UnitTestSupportTest.php.
References Motley\UnitTestSupport\clearCapturedErrors(), Motley\UnitTestSupport\disengageCaptureHandler(), Motley\UnitTestSupport\engageCaptureHandler(), Motley\UnitTestSupport\ERRSTR, and Motley\UnitTestSupport\getCapturedErrors().
testRecursiveDirectoryDelete()
Motley\Test\UnitTestSupportTest::testRecursiveDirectoryDelete ()
Test the temporary dir/file routines.
Definition at line 81 of file UnitTestSupportTest.php.
Field Documentation
$lastUnit
Motley\Test\UnitTestSupportTest::$lastUnit = null protected
Last interesting UnitTestSupport instance.
Definition at line 19 of file UnitTestSupportTest.php.
The documentation for this class was generated from the following file:
phplib/Motley/Test/UnitTestSupportTest.php